<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CsClient.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bots\Bots.csproj" />
  </ItemGroup>

</Project>
